# Copy the supplied resources; never move files or write under Source/.
cmake_minimum_required(VERSION 3.25)
foreach(required IN ITEMS LEGACY_ROOT RUNTIME_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} must name an absolute directory")
    endif()
    if(NOT IS_ABSOLUTE "${${required}}")
        message(FATAL_ERROR "${required} must be absolute")
    endif()
endforeach()
if(NOT IS_DIRECTORY "${LEGACY_ROOT}/monopoly")
    message(STATUS "Source resource corpus absent; no resources copied")
    return()
endif()
# Resolve the existing ancestor first: REAL_PATH on a not-yet-created
# directory warns on newer CMake versions and cannot inspect its junctions.
function(canonical_destination input result)
    get_filename_component(cursor "${input}" ABSOLUTE)
    cmake_path(NORMAL_PATH cursor)
    set(suffix "")
    while(NOT EXISTS "${cursor}")
        if(IS_SYMLINK "${cursor}")
            message(FATAL_ERROR "Dangling resource destination link: ${cursor}")
        endif()
        cmake_path(GET cursor FILENAME component)
        cmake_path(GET cursor PARENT_PATH parent)
        if(parent STREQUAL cursor)
            message(FATAL_ERROR "No existing ancestor for ${input}")
        endif()
        if(suffix STREQUAL "")
            set(suffix "${component}")
        else()
            set(suffix "${component}/${suffix}")
        endif()
        set(cursor "${parent}")
    endwhile()
    file(REAL_PATH "${cursor}" resolved)
    if(NOT suffix STREQUAL "")
        string(APPEND resolved "/${suffix}")
    endif()
    cmake_path(NORMAL_PATH resolved)
    set(${result} "${resolved}" PARENT_SCOPE)
endfunction()

file(REAL_PATH "${LEGACY_ROOT}" legacy_root)
file(REAL_PATH "${LEGACY_ROOT}/monopoly" source_root)
canonical_destination("${RUNTIME_DIR}" runtime_root)

# Compare canonical paths, case-insensitively on Windows. Also resolve each
# destination parent below, so a junction cannot redirect writes into Source/.
function(is_inside parent child result)
    if(CMAKE_HOST_WIN32)
        string(TOLOWER "${parent}" parent)
        string(TOLOWER "${child}" child)
    endif()
    cmake_path(IS_PREFIX parent "${child}" NORMALIZE inside)
    set(${result} "${inside}" PARENT_SCOPE)
endfunction()
is_inside("${legacy_root}" "${runtime_root}" inside_source)
is_inside("${runtime_root}" "${legacy_root}" contains_source)
if(inside_source OR contains_source)
    message(FATAL_ERROR "Resource source and destination must not overlap")
endif()
file(MAKE_DIRECTORY "${runtime_root}")

function(safe_destination relative result)
    set(target "${runtime_root}/${relative}")
    cmake_path(GET target PARENT_PATH parent)
    # REAL_PATH resolves existing junctions before any directory is created.
    canonical_destination("${parent}" resolved_parent)
    is_inside("${runtime_root}" "${resolved_parent}" inside_runtime)
    is_inside("${legacy_root}" "${resolved_parent}" inside_legacy)
    if(NOT inside_runtime OR inside_legacy OR IS_SYMLINK "${target}")
        message(FATAL_ERROR "Unsafe resource destination: ${target}")
    endif()
    file(MAKE_DIRECTORY "${parent}")
    canonical_destination("${parent}" resolved_parent)
    is_inside("${runtime_root}" "${resolved_parent}" inside_runtime)
    if(NOT inside_runtime)
        message(FATAL_ERROR "Resource destination escapes runtime directory")
    endif()
    set(${result} "${target}" PARENT_SCOPE)
endfunction()

function(stage_resource relative destination category)
    set(input "${source_root}/${relative}")
    file(REAL_PATH "${input}" resolved_input)
    is_inside("${source_root}" "${resolved_input}" inside_corpus)
    if(NOT inside_corpus OR IS_SYMLINK "${input}")
        message(FATAL_ERROR "Resource source escapes the supplied corpus: ${input}")
    endif()
    safe_destination("${destination}" output)
    file(SHA256 "${input}" source_hash)
    if(category STREQUAL "archive" AND EXISTS "${output}")
        file(SHA256 "${output}" old_hash)
        if(NOT old_hash STREQUAL source_hash)
            message(FATAL_ERROR "Refusing to overwrite a different DAT bank: ${output}")
        endif()
    endif()
    file(COPY_FILE "${input}" "${output}" ONLY_IF_DIFFERENT)
    file(SHA256 "${output}" destination_hash)
    if(NOT source_hash STREQUAL destination_hash)
        message(FATAL_ERROR "Resource copy differs from original: ${relative}")
    endif()
    file(SIZE "${output}" size)
    set_property(GLOBAL APPEND PROPERTY staged_rows
        "${category}\t${relative}\t${destination}\t${size}\t${source_hash}\n")
    set_property(GLOBAL APPEND PROPERTY "staged_${category}" "${destination}")
endfunction()

# These directories are resolved directly by TextureCatalog from the runtime
# root. Flattening them or copying only to assets/legacy breaks their lookups.
file(GLOB_RECURSE candidates LIST_DIRECTORIES false
    RELATIVE "${source_root}" "${source_root}/*")
list(SORT candidates)
foreach(relative IN LISTS candidates)
    string(TOLOWER "${relative}" lower)
    if(lower MATCHES "\\.bmp$")
        stage_resource("${relative}" "${relative}" image)
    elseif(lower MATCHES "(^qhelp[0-9][0-9]\\.txt$|\\.hlp$|^license[^/]*\\.txt$)"
        OR lower MATCHES "^(boards|cities|currency|languages)/.*\\.txt$")
        stage_resource("${relative}" "${relative}" support)
    elseif(lower MATCHES "^dat_mon/[^/]+\\.dat$")
        # Actual archives only. Headers are reconstruction inputs, not banks.
        cmake_path(GET lower FILENAME bank)
        stage_resource("${relative}" "Dat_Mon/${bank}" archive)
    elseif(lower MATCHES "\\.(wav|bik|avi|cnk|hmd|uap)$")
        stage_resource("${relative}" "${relative}" media)
    elseif(lower MATCHES "^dat_mon/[^/]+\\.h$" OR
        lower STREQUAL "english.a" OR lower STREQUAL "english.atr")
        stage_resource("${relative}" "assets/reconstruction/${relative}" reconstruction)
    endif()
endforeach()

# Preserve the paths used by the existing background and AI owners too.
foreach(background IN ITEMS BackGround.bmp BackGroundEuro.bmp)
    if(EXISTS "${source_root}/${background}")
        stage_resource("${background}" "assets/legacy/${background}" alias)
    endif()
endforeach()
foreach(profile IN ITEMS Cannon.ai RaceCar.ai Dog.ai TopHat.ai Iron.ai Horse.ai
    Boot.ai Ship.ai Thimble.ai Barrow.AI Moneybag.ai Normal.ai)
    string(TOLOWER "${profile}" expected)
    foreach(relative IN LISTS candidates)
        string(TOLOWER "${relative}" lower)
        if(lower STREQUAL expected)
            stage_resource("${relative}" "assets/ai/${profile}" ai)
            break()
        endif()
    endforeach()
endforeach()

set(summary "Source resource copies, not a complete retail installation.\n")
set(report "category\tsource_relative\truntime_relative\tbytes\tsha256\n")
get_property(rows GLOBAL PROPERTY staged_rows)
foreach(row IN LISTS rows)
    string(APPEND report "${row}")
endforeach()
foreach(category IN ITEMS image ai support media reconstruction archive alias)
    get_property(items GLOBAL PROPERTY "staged_${category}")
    list(LENGTH items count)
    string(APPEND summary "${category}: ${count}\n")
    set("count_${category}" "${count}")
endforeach()
set(missing)
foreach(bank IN ITEMS dat_main.dat dat_pat.dat dat_bord.dat dat_brd2.dat
    dat_3d.dat dat_ln01.dat dat_lm01.dat dat_lk01.dat)
    if(NOT EXISTS "${runtime_root}/Dat_Mon/${bank}")
        list(APPEND missing "${bank}")
        string(APPEND summary "MISSING required bank: Dat_Mon/${bank}\n")
    else()
        string(APPEND summary "PRESENT bank, contents not validated: Dat_Mon/${bank}\n")
    endif()
endforeach()
string(APPEND summary "\nImages are copied unchanged. No DAT archive or absent animation/sound was fabricated.\n")
safe_destination("assets/resource-copies.tsv" report_path)
safe_destination("assets/resource-status.txt" summary_path)
file(WRITE "${report_path}" "${report}")
file(WRITE "${summary_path}" "${summary}")
message(STATUS "Resources staged: ${count_image} images, ${count_ai} AI profiles, ${count_support} support files; originals unchanged")
if(missing)
    list(JOIN missing ", " missing_names)
    message(STATUS "Required DAT banks still missing: ${missing_names}")
endif()
