#pragma once

#include "DataBanks.hpp"

#include <cstdint>
#include <optional>

namespace monopoly::udsound
{
    enum class PennybagsVoice : std::uint16_t
    {
        WelcomeGame_old = 0,
        Menu_old = 1,
        ChooseNetworkOrLocalGame_old = 2,
        NoUserInputForXSeconds_old = 3,
        HumanPlayerPickToken_old = 4,
        ChoosePlayer_HumanOrComputer_old = 5,
        ChooseTokenForComputerPlayer_old = 6,
        NewPlayerEnterNameOrPickFromList_old = 7,
        NewPlayerEnterName_old = 8,
        ChooseAIDifficultyLevel_old = 9,
        ChooseClassicOrCityBoard_AnyVersion_old = 10,
        ChooseStandardOrCustomRules_old = 11,
        SummaryScreen_old = 12,
        GameStarted_old = 13,
        NegotiateRules_old = 14,
        PromptEachPlayerForCustomRulesConfirmation_old = 15,
        CustomRulesAgreedOnStartGame_old = 16,
        MainScreenIntro_old = 17,
        RollDice_Cannon = 18,
        RollDice_Car = 19,
        RollDice_Dog = 20,
        RollDice_Hat = 21,
        RollDice_Iron = 22,
        RollDice_Horse = 23,
        RollDice_Ship = 24,
        RollDice_Shoe = 25,
        RollDice_Thimble = 26,
        RollDice_Wheelbarrow = 27,
        RollDice_SackOfMoney = 28,
        RollDice_Generic = 29,
        SayDiceRoll_2 = 30,
        SayDiceRoll_3 = 31,
        SayDiceRoll_4 = 32,
        SayDiceRoll_5 = 33,
        SayDiceRoll_6 = 34,
        SayDiceRoll_7 = 35,
        SayDiceRoll_8 = 36,
        SayDiceRoll_9 = 37,
        SayDiceRoll_10 = 38,
        SayDiceRoll_11 = 39,
        SayDiceRoll_12 = 40,
        TokenLandsOnUnownedProperty = 41,
        BuyBoardSide1 = 42,
        BuyBoardSide2 = 43,
        BuyBoardSide3 = 44,
        BuyBoardSide4 = 45,
        BuyRailroad = 46,
        BuyUtility = 47,
        LandOn_Chance = 48,
        LandOn_CommunityChest = 49,
        ChanceCard = 50,
        CommunityChestCard = 51,
        LandOn_JustVisiting = 52,
        LandOn_FreeParking = 53,
        LandOn_FreeParkingWithFreeParkingRuleOn = 54,
        LandOn_GoToJail_Negative = 55,
        LandOn_GoToJail_Positive = 56,
        JailPayMoneyOrTryForDoubles = 57,
        CollectMoney_Go = 58,
        CollectMoney_LandedOnGoAndDoublePayRuleInEffect = 59,
        LandOn_LuxuryTax = 60,
        LandOn_IncomeTax = 61,
        Auction = 62,
        Auction_ExplanationOnButtonsToIncreaseBid = 63,
        Auction_OpeningBid = 64,
        Auction_CallOutTokenWithHighestBid = 65,
        Auction_GoingOnce = 66,
        Auction_GoingTwice = 67,
        Auction_GoingSold = 68,
        Auction_CongratulateWinner = 69,
        PlayerClicks_Mortgage = 70,
        PlayerClicks_UnMortgage = 71,
        PlayerClicks_BuyHouseHotel = 72,
        PlayerClicks_SellHouseHotel = 73,
        PlayerAcquiredMonopoly = 74,
        PlayerBuiltFirstHouse = 75,
        PlayerBuiltFirstHotel = 76,
        StatusScreen_FirstTime = 77,
        StatusScreen_FirstTimeDeeds = 78,
        StatusScreen_FirstTimeBankAssets = 79,
        Calculator = 80,
        TradeScreen = 81,
        TradeScreen_ProposeClickedButOneSideHasNotOfferedAnything = 82,
        TradeScreen_ThirdPartyTradeExplanation = 83,
        TradeScreen_PickTradePartner = 84,
        TradeScreen_TradeComplete = 85,
        TradeScreen_TradeCancelled = 86,
        HousingShortage_FirstTimeHouses = 87,
        HousingShortage_FirstTimeHotels = 88,
        HousingShortage_NotFirstTime = 89,
        Auction_HurryPlayersBid = 90,
        Auction_Building = 91,
        Auction_Once = 92,
        Auction_Twice = 93,
        Auction_LostTimeUp = 94,
        RaisingMoneySuggestion = 95,
        HumanReplacedByComputerPlayer = 96,
        Trade_FirstTimeFuture = 97,
        Trade_FirstTimeImmunity = 98,
        Bankrupt = 99,
        GameOver = 100,
        PlayAgain = 101,
        Exit = 102,
        Proposal_GoodDeal = 103,
        Proposal_NotGoodDeal = 104,
        BoardSquareNames_US = 105,
        WelcomeGame = 106,
        AnnouncePreviousHighScoresIfAny = 107,
        ChooseNetworkOrLocalGame = 108,
        NewPlayerClickNameOrPressButton = 109,
        NewPlayerEnterName = 110,
        NameComputerPlayer = 111,
        HumanPlayerPickToken = 112,
        ChooseTokenForComputerPlayer = 113,
        ChoosePlayer_HumanOrComputer = 114,
        ChooseAIDifficultyLevel = 115,
        SummaryScreenWithLessThanTwoPlayers = 116,
        SummaryScreenWithTwoToFivePlayers = 117,
        SummaryScreenWithSixPlayers = 118,
        ChooseClassicOrCityBoard_AnyVersion = 119,
        ChooseClassicOrCityBoard_Europe = 120,
        ChooseClassicOrCityBoard_US = 121,
        ChooseCurrency = 122,
        ChooseStandardOrCustomRules = 123,
        NegotiateRules = 124,
        Doubles = 125,
        RollAgain = 126,
        SecondTimeRollingDoubles = 127,
        ThirdTimeRollingDoubles = 128,
        CustomRulesScreenHost = 129,
        NonhostPlayersWatchRuleChange = 130,
        HumanInitiatesTrade = 131,
        AIInitiatesTrade = 132,
        Count
    };

    static_assert(static_cast<std::uint16_t>(PennybagsVoice::Count) == 133);

    struct PennybagsChoice
    {
        data::DataTag firstTag{};
        std::uint8_t alternateCount{};
    };

    [[nodiscard]] const PennybagsChoice* pennybagsChoice(
        data::BoardEdition edition, PennybagsVoice voice) noexcept;
    [[nodiscard]] std::optional<data::DataId> pennybagsVoiceAt(
        data::BoardEdition edition, PennybagsVoice voice,
        std::uint8_t alternateIndex) noexcept;
    [[nodiscard]] std::optional<data::DataId> choosePennybagsVoice(
        data::BoardEdition edition, PennybagsVoice voice,
        std::uint32_t randomValue) noexcept;
}
